### ISSUE TITLE
"entries" doesn't work

### ISSUE THREAD

**Issue by darrencruse** [kantord/emuto-demo#322]
was playing with emuto demo here just learning:
https://kantord.github.io/emuto/docs/try_emuto

and when I try the example for "entries" shown here:
https://kantord.github.io/emuto/docs/functions#entries

I get the error in the screenshot below

(I snooped in the repo here and it looks like it's that emuto-demo isn't using the latest version of emuto?  does that mean the project has maybe stalled out and isn't being maintained anymore?)

![Screenshot 2021-08-28 2 47 36 PM](https://user-images.githubusercontent.com/1283688/131229437-fafb383d-0e39-4845-b0da-9a9b612fe99b.png)

**Comment by kantord** [comment]
![2021-08-29T14:38:42+02:00](https://user-images.githubusercontent.com/3704904/131250611-eb5ee6cf-e7d6-4665-ad5a-64a4db8ced27.png)

looks like this works in emuto itself, it must be that the emuto version is outdate in the demo 👀

**Comment by kantord** [comment]
thanks for reporting @darrencruse
